name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20
    - run: npm ci
    - name: Install the browsers
      run: npx playwright install --with-deps
    - name: Run end-to-end tests
      run: npm test
      continue-on-error: true  # This will allow the pipeline to continue even if tests fail

    - name: Show Playwright test report if failed
      if: failure()  # Only runs if the previous step fails
      run: |
        echo "Playwright tests failed. Displaying the HTML report."
        cat playwright-report/index.html 
    - run: npx nyc report --reporter=lcovonly
    - name: Upload to Coveralls
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

